workflows:
  build-and-upload-ipa:
    name: Build and Upload IPA (Final Robust Method)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - |
        # Step 1: Build the .app file
        echo "Building .app file..."
        flutter build ios --release --no-codesign
      - |
        # Step 2: Create the .ipa file manually in the root directory
        echo "Creating IPA manually..."
        cd build/ios/iphoneos/
        mkdir Payload
        mv Runner.app Payload/
        zip -r ../../../newhayekjewel.ipa Payload/
        cd ../../..
      - |
        # Step 3: Upload the IPA file from the correct path
        echo "Uploading to Transfer.sh..."
        DOWNLOAD_URL=$(curl --upload-file ./newhayekjewel.ipa https://transfer.sh/newhayekjewel.ipa)
        echo "===================================================================="
        echo "DOWNLOAD YOUR IPA FILE FROM THIS LINK:"
        echo $DOWNLOAD_URL
        echo "===================================================================="
    artifacts:
      - ./*.ipa # Keep as a fallback
