workflows:
  # === سير عمل بناء نسخة المحاكي (للتأكد أن البناء سليم) ===
  simulator-build:
    name: Simulator Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ios --simulator --no-codesign
    artifacts:
      - build/ios/**/*.app

  # === سير العمل الجديد والصحيح لبناء ملف IPA ===
  build-ios-ipa:
    name: Build iOS IPA
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ipa --release --no-codesign
      - |
        echo "Exporting the .ipa file from the archive..."
        xcodebuild -exportArchive \
          -archivePath build/ios/archive/Runner.xcarchive \
          -exportPath build/ios/ipa \
          -exportOptionsPlist $CM_BUILD_DIR/ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
