workflows:
  build-ios-ipa:
    name: Build iOS IPA for Sideloading
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - |
        # بناء الأرشيف أولاً
        flutter build ipa --release --no-codesign
      - |
        # تصدير الأرشيف إلى ملف IPA
        xcodebuild -exportArchive \
          -archivePath build/ios/archive/Runner.xcarchive \
          -exportPath build/ios/ipa \
          -exportOptionsPlist $CM_BUILD_DIR/ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
