# Start of Codemagic YAML file

workflows:
  simulator-build:
    name: Simulator Build
    environment:
      flutter: stable
      xcode: latest
    
    scripts:
      - |
        echo "Installing Flutter dependencies..."
        flutter pub get
      - |
        echo "Building for iOS simulator..."
        flutter build ios --release --simulator
    
    artifacts:
      - build/ios/simulator/*.app
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: false
