workflows:
  # === سير العمل القديم لبناء نسخة المحاكي (للتأكد أن البناء سليم) ===
  simulator-build:
    name: Simulator Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ios --simulator --no-codesign
    artifacts:
      - build/ios/**/*.app

  # === سير العمل الجديد لبناء ملف IPA خام (الذي سنستخدمه الآن) ===
  build-ios-unsigned-ipa:
    name: Build Unsigned iOS IPA
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
