workflows:
  build-and-upload-ipa:
    name: Build and Upload IPA (Transfer.sh)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - |
        # الخطوة 1: بناء ملف .app العادي
        echo "Building .app file..."
        flutter build ios --release --no-codesign
      - |
        # الخطوة 2: إنشاء ملف .ipa يدويًا
        echo "Creating IPA manually..."
        mkdir -p build/ios/Payload
        cp -r build/ios/iphoneos/Runner.app build/ios/Payload/
        cd build/ios
        zip -r ../../../newhayekjewel.ipa Payload
        cd ../..
      - |
        # الخطوة 3: رفع الملف إلى خدمة خارجية وطباعة الرابط
        echo "Uploading to Transfer.sh..."
        DOWNLOAD_URL=$(curl --upload-file ./newhayekjewel.ipa https://transfer.sh/newhayekjewel.ipa )
        echo "===================================================================="
        echo "===================================================================="
        echo "DOWNLOAD YOUR IPA FILE FROM THIS LINK:"
        echo $DOWNLOAD_URL
        echo "===================================================================="
        echo "===================================================================="
    artifacts:
      - ./*.ipa # سنبقيه كاحتياط
