    # Start of Codemagic YAML file

    workflows:
      default-workflow:
        name: Default Workflow
        environment:
          flutter: stable
          xcode: latest
          # Ensure you have a valid signing configuration for iOS builds.
          # You may need to add a `signing` section later if you plan to publish to the App Store.
        
        scripts:
          - |
            echo "Installing Flutter dependencies..."
            flutter pub get
          - |
            echo "Building iOS IPA..."
            flutter build ios --release --no-codesign

        artifacts:
          - build/ios/ipa/*.ipa

        publishing:
          email:
            recipients:
              - your-email@example.com
            notify:
              success: true
              failure: false
    