workflows:
  simulator-build:
    name: Simulator Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ios --simulator --no-codesign
    artifacts:
      - build/ios/simulator/*.app
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: false
