name: hayekjewel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase (كلها متوافقة مع بعض)
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  cloud_functions: ^5.0.4
  firebase_storage: ^12.1.2
  firebase_messaging: ^15.1.3

  # باقي المكتبات
  provider: ^6.1.2
  http: ^1.2.2
  html: ^0.15.4
  image_picker: ^1.1.2
  marquee: ^2.2.3
  photo_view: ^0.15.0
  cached_network_image: ^3.4.0
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.1.0
  carousel_slider: ^5.0.0
  flutter_local_notifications: ^17.2.3
  uuid: ^4.5.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/bk.png
    - ./.env
