name: newhayekjewel
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  cloud_firestore: ^5.6.0
  cloud_functions: ^5.2.0 # Add this line
  provider: ^6.1.2
  http: ^1.2.2
  html: ^0.15.0
  twilio_flutter: ^0.9.0
  firebase_storage: ^12.4.0
  image_picker: ^1.1.2
  marquee: ^2.3.0
  photo_view: ^0.15.0
  cached_network_image: ^3.2.3
  shared_preferences: ^2.3.5





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/bk.png