# Start of Codemagic YAML file

workflows:
  simulator-build:
    name: Simulator Build
    environment:
      flutter: stable
      xcode: latest
    
    scripts:
      - |
        echo "Installing Flutter dependencies..."
        flutter pub get
      - |
        echo "Running pod install..."
        cd ios
        pod install --repo-update
        cd ..
      - |
        echo "Building for iOS simulator..."
        flutter build ios --simulator
    
    artifacts:
      - build/ios/simulator/*.app
    
    publishing:
      email:
        recipients:
          - eng.alhayek@icloud.com
        notify:
          success: true
          failure: true
