// This file is auto-generated by the Firebase CLI.
// To update these options, run:
// `flutterfire configure`

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPxWk_xLw6P_4P4yP4yP4yP4yP4yP4yP4yP4yP',
    appId: '1:178317324117:web:9b0ab1d3a1a3d3e08711dc',
    messagingSenderId: '178317324117',
    projectId: 'alhayekjewelry-7ff5e',
    authDomain: 'alhayekjewelry-7ff5e.firebaseapp.com',
    storageBucket: 'alhayekjewelry-7ff5e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPxWk_xLw6P_4P4yP4yP4yP4yP4yP4yP4yP4yP',
    appId: '1:178317324117:android:9b0ab1d3a1a3d3e08711dc',
    messagingSenderId: '178317324117',
    projectId: 'alhayekjewelry-7ff5e',
    storageBucket: 'alhayekjewelry-7ff5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPxWk_xLw6P_4P4yP4yP4yP4yP4yP4yP4yP4yP',
    appId: '1:178317324117:ios:9b0ab1d3a1a3d3e08711dc',
    messagingSenderId: '178317324117',
    projectId: 'alhayekjewelry-7ff5e',
    storageBucket: 'alhayekjewelry-7ff5e.appspot.com',
    iosBundleId: 'com.example.newhayekjewel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPxWk_xLw6P_4P4yP4yP4yP4yP4yP4yP4yP4yP',
    appId: '1:178317324117:macos:9b0ab1d3a1a3d3e08711dc',
    messagingSenderId: '178317324117',
    projectId: 'alhayekjewelry-7ff5e',
    storageBucket: 'alhayekjewelry-7ff5e.appspot.com',
    iosBundleId: 'com.example.newhayekjewel',
  );
}
